name: 'Github actions deployer rsync'
description: 'Deployment Environment rsync'
inputs:
  SSH_HOST:
    description: 'Host SSH'
    required: true
  SSH_PORT:
    description: 'Port SSH'
    required: false
    default: '22'
  SSH_USER:
    description: 'User SSH'
    required: true
  SSH_KEY:
    description: 'Key SSH'
    required: true
  PATH_PUBLIC:
    description: 'Path deployment'
    required: true
  FILES_IGNORE:
    description: 'List of directories and files to be ignored between releases'
    required: false
    default: ''
  BRANCH_NAME:
    description: 'Branch name deployment'
    required: true
  DEPLOY_DOMAIN:
    description: 'Deploy domain'
    required: false
    default: ''
  USERNAME:
    description: 'User performing the deployment'
    required: true
  GITHUB_TOKEN:
    description: 'Token Github'
    required: true
  GITHUB_REPOSITORY:
    description: 'Repository Github'
    required: true
  KEEP_RELEASES:
    description: 'Number of releases stored'
    required: false
    default: 5
  COMPOSER:
    description: 'Perform composer'
    type: boolean
    required: false
    default: false
  COMPOSER_RUN_SCRIPTS:
    description: 'List of composer run script commands'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SSH_HOST }}
    - ${{ inputs.SSH_PORT }}
    - ${{ inputs.SSH_USER }}
    - "${{ inputs.SSH_KEY }}"
    - ${{ inputs.PATH_PUBLIC }}
    - ${{ inputs.FILES_IGNORE }}
    - ${{ inputs.BRANCH_NAME }}
    - ${{ inputs.DEPLOY_DOMAIN }}
    - ${{ inputs.USERNAME }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.GITHUB_REPOSITORY }}
    - ${{ inputs.KEEP_RELEASES }}
    - ${{ inputs.COMPOSER }}
    - ${{ inputs.COMPOSER_RUN_SCRIPTS }}
branding:
  icon: 'upload-cloud'
  color: 'blue'